"""add tags table and post_tags relationship

Revision ID: 3fbb433d69a1
Revises: dc94b3ff0065
Create Date: 2025-11-05 15:25:57.161970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbb433d69a1'
down_revision: Union[str, Sequence[str], None] = 'dc94b3ff0065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('tags', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
